from nnicotine.datasets.cath import _length_mismatch_resolve_gaps

strucseq = "B--CD-FG"
strucseq = [x for x in strucseq]
refseq = "ABCDEFGHI"

# strucseq =  "H--QAEILLTLKLQQKLFADPRRISLLKHIALSGSISQGAKDAGISYKSAWDAINE-NQLSEHILVER---------AVLTRYGQRLIQLYDLLAQIQQKAFDVLSDDD"
# strucseq = [x for x in strucseq]
# refseq = "GSHMQAEILLTLKLQQKLFADPRRISLLKHIALSGSISQGAKDAGISYKSAWDAINEMNQLSEHILVERATGGKGGGGAVLTRYGQRLIQLYDLLAQIQQKAFDVLSDDDALPLNSLLAAISRFSLQTSARNQWFGTITARDHDDVQQHVDVLLADGKTRLKVAITAQSGARLGLDEGKEVLILLKAPWVGITQDEAVAQNADNQLPGIISHIERGAEQCEVLMALPDGQTLCATVPVNEATSLQQGQNVTAYFNADSVIIATLC"

_length_mismatch_resolve_gaps(strucseq, refseq)
